version: "3.4"

services:
  webapi:
    container_name: linguagem-ubiqua
    image: linguagem-ubiqua/net6
    environment:
      - PORT=8000
    ports:
      - 8000:80
    build:
      context: .
      dockerfile: Dockerfile
